### ISSUE TITLE
Batch warnings to show once per instance

### ISSUE THREAD

**Issue by guanzo** [atomiks/tippyjs#746] opened 2020-03-30 02:14 UTC
## Problem

tippy.js's huge warnings hog the console. I understand the warning, it is acknowledged

## Solution

Let me disable warnings so it stops flooding the console. No, I don't want to toggle "Default Levels" in the devtools, b/c I care about other potential warnings.

![](https://i.gyazo.com/fc0869be3af504d461b0eb2f9dc55425.png)

**Comment by atomiks** [comment] 2020-03-30 08:11
> I understand the warning, it is acknowledged

Why can't you fix it? 

In this case batching the warning to only show once for a certain instance would be better though. This particular warning can be silenced (as it says) by specifying `appendTo={document.body}`; accessibility will be broken either way.

If you really want to turn all of them off you should be able to run the `tippy.js` package in production mode (replace `process.env.NODE_ENV` with `"production"`) and they'll go away.

**Comment by guanzo** [comment] 2020-03-30 08:51
The problem is, `appendTo={document.body}` changes the positioning behavior, it made the tooltip fixed in the viewport instead of sticky to the reference, while scrolling.

I tried the wrapper fix but it interfered with a css framework yadda yadda.

Batching warnings per instance is a good compromise, though personally I think one global warning is enough. It's quite a noticeable warning, really hard to miss. Once you've seen it, you've seen it forever.

I don't want to turn them all off, i don't even know what other warnings there are, but i know about this one and want to deal with it.

**Comment by atomiks** [comment] 2020-03-30 09:46
> The problem is, appendTo={document.body} changes the positioning behavior, it made the tooltip fixed to the viewport instead of fixed to the reference element, while scrolling.

This shouldn't happen, it would be bug if so (in Popper). Reproduction? All non-interactive tippies would be suffering from this problem if that's the case.

Once per instance is necessary because you may have other instances with an accessibility problem as well. Of course you can fix them one-at-a-time with a single warning, but I think emitting multiple warnings immediately shows the scope of the issues in terms of how many problems there are.

**Comment by guanzo** [comment] 2020-03-30 22:03
I could not reproduce it with an isolated example, I can only reproduce it by loading my entire app. Maybe that means something in my app is interfering with popper.js? 

Reproduction steps:
1. `$ git clone https://github.com/guanzo/debug-popper.git`
2. `$ cd debug-popper/client`
3. `$ npm install`
4. `$ npm run serve`
5. In your browser, navigate to https://localhost:8050/config.html. If port 8050 was not available, check the console for the actual url.
6. Shrink your window vertically to force a vertical scrollbar.
7. Hover over any `<input/>` under any of the 3 "X Color" labels.
![](https://i.gyazo.com/b1197bdc0f427be332b68ce93e9f9cec.png)
8. See the popper appear, then scroll up/down. The popper is fixed to the viewport.

The relevant file is `Theme.vue`.
The tippy instantiation is inside the `mounted()` function. The reference and popper element are at the top of the tile, inside the `<template>`.

If you comment out `appendTo: document.body,`, the popper becomes fixed to the reference, which is the desired behavior. (Also this is where the warning appears XD).

**Comment by atomiks** [comment] 2020-03-31 08:13
@guanzo thanks that was helpful, I discovered the bug in Popper. I'll make a PR for a fix.

**Comment by guanzo** [comment] 2020-03-31 08:23
awesome awesome awesome. that reproduction took some time to setup, glad it was worth it.

**Comment by atomiks** [comment] 2020-03-31 08:29
By the way for now, you should be able to specify `appendTo: "parent"` and everything will be fixed (no warning, or that bug).

**Closed** 2020-04-03 02:23 UTC
Labels: 💎 enhancement
