### ISSUE TITLE
`showOnCreate` prop should respect `followCursor` 

### ISSUE THREAD

**Issue by AngelCastellanosSegundo** [atomiks/tippyjs#650] opened 2019-12-05 10:47 UTC
## Bug description

A few weeks ago we opened a bug (code #634) in which we indicated that when displaying the tooltip for the first time in an event with the showOnCreate property, delay and followCursor were not respected. The problem with the delay has been corrected, but we still have the problem with the followCursor.

We have detected that the error occurs with Chrome (v78) and Firefox (v70), but with Internet Explorer (v11) it works correctly.

## Reproduction

In the same request indicated above (#634) a CodePen was attached in which we see that the incidence can be reproduced.
CodePen link: https://codepen.io/atomiks/pen/wvvyQmQ

The error is reproduced as follows:
- Place the cursor on the button (It is the first time that the onmouseover event is executed, so the tippy instance will be created and displayed thanks to the showOnCreate property). The tooltip will appear in a centered position.
- Move the cursor from the button.
- Reposition the cursor over the button (It is the second time the onmouseover event is executed). Now the tooltip will appear in its correct position, next to the cursor.

We have recorded a video reproducing the error with the CodePen.
[Tippy.js issue #634.zip](https://github.com/atomiks/tippyjs/files/3926361/Tippy.js.issue.634.zip)

**Comment by atomiks** [comment] 2019-12-05 11:00
> We have detected that the error occurs with Chrome (v78) and Firefox (v70), but with Internet Explorer (v11) it works correctly.

Now isn't that ironic 😆 

---

It's weird because for me, it works correctly in Chrome, but not in Firefox. Hunting down these async bugs is kind of nightmarish but I'll see what I can do.

**Comment by AngelCastellanosSegundo** [comment] 2019-12-05 11:21
Ok, thank you very much and good luck in your hunt. 🙂
As for IE11, it must be the first time I say "it works in IE11 and not in Chrome"... 😅

**Comment by atomiks** [comment] 2019-12-20 04:53
It works if you use `tippy.delegate()`: https://codepen.io/atomiks/pen/wvvyQmQ

I would recommend using that instead.

**Comment by AngelCastellanosSegundo** [comment] 2019-12-20 09:39
I think it doesn't work for us. We need the content of the tooltip to be dynamic and with this solution it seems that it is not. We have created a new codepen by changing the text shown by a dynamic one and it is not updated between buttons.

https://codepen.io/AngelCastellanos/pen/NWPpymE

**Comment by atomiks** [comment] 2019-12-20 09:44
Making it a thunk will work: `content: () => new Date()`. It will get called for each new instance that gets created.

**Comment by AngelCastellanosSegundo** [comment] 2019-12-23 08:49
We need to activate the tooltip in the OnMouseOver event in certain elements, not all of the same type, so this solution is not valid for us, since you cannot pass the selector and the text as we need.
On the other hand, we have created a new Codepen with a table structure more similar to what we need. We have added the event we use and created the tooltip as you have indicated. First, we see that a problem occurs when taking the text, because it is not updated; second, we see that the problem of displaying the first tooltip in the center of the cell continues to occur.
This is de CodePen:
https://codepen.io/AngelCastellanos/pen/MWYmQOP

**Comment by atomiks** [comment] 2019-12-23 08:58
The problem is Firefox doesn't fire the `mouseenter` event after the `mouseover` event (which is when the instance and event listeners first get added), and `followCursor` hooks into `onTrigger`, so it doesn't work on the first show.

Your problem can be solved like this: https://codepen.io/atomiks/pen/LYEydNb?editors=1010

If you need more elements to be targets, make an array and loop over them and create a new delegate instance for the targets.

**Comment by AngelCastellanosSegundo** [comment] 2019-12-23 10:26
La creacion de mi tabla se hace dinamicamente con dhtmlx, por lo que no puedo usar el metodo delegado y tengo que poder pasarle como parametros el selector en el que se debe activar y el texto que debe mostrar. Tenemos que lanzar el tooltip en el evento onmouseover, no aparte.

**Comment by atomiks** [comment] 2020-03-18 06:27
I don't think this is something that will be fixed, especially with the `multiple` prop gone in v6. The techniques being used for this should just be avoided in the first place.

**Closed by atomiks** 2020-03-18 06:27 UTC
Labels: 🐛 bug
