### ISSUE TITLE
Removing a persistent tooltip breaks input on iOS

### ISSUE THREAD

**Issue by Christian24** [atomiks/tippyjs#78] opened 2017-07-12 10:34 UTC
I create a html persistent tippy like this: 
```typescript
   const tip = this.tippy(this.currentStep.element, {html: this.template, // OR document.querySelector('#my-template-id')
        arrow: true,
        animation: "fade",
        trigger: "manual",
        sticky: true,
        hideOnClick: "persistent",
      theme: "light"});
      console.log(tip);
      const popper =  tip.getPopperElement(this.currentStep.element);
      tip.show(popper);

this.tip = tip;
this.popper = popper;
```
This works fine. However, when I remove the tip with ` this.tip.hide(this.popper);` the tooltip disappears, but I also can no longer press any buttons/links on iOS devices. Before it works fine, but after I remove the tooltip "click" input is broken. I also tried `this.tip.destroyAll();` but the issue is the same.

Thanks a lot in advance.

**Comment by atomiks** [comment] 2017-07-12 14:29
Can you please make a CodePen demonstrating the behavior?

**Comment by atomiks** [comment] 2017-07-28 09:20
Closing since no reply and can't reproduce...

**Closed by atomiks** 2017-07-28 09:20 UTC
