### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by lyz810** [atomiks/tippyjs#1037] opened 2022-03-14 08:20 UTC
## Bug description

dependency @popperjs/core publish a new version and has a bug, cause tippyjs install fail

The package @popperjs/core@2.11.3 meta data in https://registry.npmjs.org/@popperjs%2fcore has a postinstall, which in previous version is _postinstall, so after install the package, it will try to execute `husky install .config/husky`

## Reproduction
`npm i tippy.js`
or
`npm i @popperjs/core`

```
npm ERR! command failed
npm ERR! command sh -c husky install .config/husky
npm ERR! sh: husky: command not found
```

I know this bug belongs to @popperjs/core, but it seems to be moved from github, I don't known where to report this issue

I think this issue should be reported to @FezVrasta or @atomiks

**Comment by atomiks** [comment] 2022-03-14 08:31
The package.json of v2.11.3 still has a `_` in front of the `postinstall` though. How does the metadata not have it? I also can't reproduce it myself. Do you have Husky installed?

@FezVrasta has to locally publish npm packages for now as they aren't automated with the new branch setup we have unfortunately.

**Comment by atomiks** [comment] 2022-03-14 10:15
This was fixed in latest v

**Closed as completed by atomiks** 2022-03-14 10:15 UTC
Labels: 🐛 bug, 🚧 unconfirmed
