### ISSUE TITLE
Some tooltips show in top left of screen, transform has wrong values

### ISSUE THREAD

**Issue by em-rad** [atomiks/tippyjs#980] opened 2021-09-29 14:23 UTC
## Bug description

Some instances of our tippy tooltips are showing in the top-left screen of only some monitors / instances of Chrome, it can be replicated on mac & windows.

We have just started using Taiga UI & Tailwind CSS but neither explicitly touch our tooltip instances.

## Reproduction
![Screenshot (2)](https://user-images.githubusercontent.com/33489063/135286554-4fa36b0b-d475-4872-a2de-109d76908ab3.png)

![Screenshot (4)](https://user-images.githubusercontent.com/33489063/135286794-c5c096ef-b827-4248-9a29-359291f93d89.png)

Popperjs/core: 2.5.3
Popper.js: 1.16.1
Tippy.js: 6.1.0

Options:
` allowHTML: true
animateFill: false
animation: "fade"
appendTo: ()=> {…}
aria: {expanded: true, content: null}
arrow: true
content: "Text goes here"
delay: 0
duration: 100
followCursor: false
getReferenceClientRect: null
hideOnClick: true
ignoreAttributes: false
inertia: false
inlinePositioning: false
interactive: true
interactiveBorder: 2
interactiveDebounce: 0
maxWidth: 220
moveTransition: ""
offset: (2) [0, 12]
onAfterUpdate: ƒ ()
onBeforeUpdate: ƒ ()
onClickOutside: ƒ ()
onCreate: t=> {…}
onDestroy: ƒ ()
onHidden: ƒ ()
onHide: ƒ ()
onMount: ƒ ()
onShow: ƒ ()
onShown: ƒ ()
onTrigger: ƒ ()
onUntrigger: ƒ ()
placement: "bottom"
plugins: []
popperOptions: {modifiers: Array(1)}
render: ƒ H(t)
role: "tooltip"
showOnCreate: false
sticky: false
theme: "inverse"
touch: true
trigger: "mouseenter focus"
triggerTarget: null
zIndex: 9999 `

**Comment by atomiks** [comment] 2021-09-30 19:27
This usually means the reference element the tippy is positioned near doesn't exist on the DOM for some reason. The `tippyInstance.reference` property points to what?

**Comment by atomiks** [comment] 2021-10-05 08:24
Without a reproduction it's not possible to help here; closing for now

**Closed by atomiks** 2021-10-05 08:24 UTC
Labels: 🐛 bug, 🚧 unconfirmed

**Comment by MariaThermofisher** [comment] 2022-02-15 15:35
I had the same issue, [this](https://github.com/atomiks/tippyjs-react/issues/337) helped me solve it.

**Comment by eirikhm** [comment] 2022-04-05 09:33
I had the same issue, and it turns out it was related to re-rendering. Showing the tooltip in the next tick positioned it correctly.

**Comment by Aribaskar-jb** [comment] 2024-02-13 07:08
Hi How the change the transform @em-rad
