### ISSUE TITLE
Tooltips do not position correctly if the wrapper has an overflow: auto

### ISSUE THREAD

**Issue by khalidadil** [atomiks/tippyjs#257] opened 2018-07-02 21:49 UTC
I am running into a situation where an element inside a wrapper with an `overflow: auto` does not position the tooltip correctly.

This is what I'm seeing (tippy v2.5.3):
https://codepen.io/khalidadil/pen/GGeMrr

When I try creating a simple popup using popperJS (v1.14.3) and the same HTML, it seems to work:
https://codepen.io/khalidadil/pen/pKYWxG

**Comment by atomiks** [comment] 2018-07-02 23:02
Thanks for reporting, but it's a Popper.js issue. Change the reference to this in the Popper.js CodePen:

```js
const refEl = document.querySelector('.convertedValue');
```

You were using the wrapper element, not the child. 

Dupe of #196

**Closed by atomiks** 2018-07-02 23:02 UTC
