### ISSUE TITLE
Tooltip problem when moving cursor fast

### ISSUE THREAD

**Issue by bilalmalkoc** [atomiks/tippyjs#379] opened 2018-12-07 19:59 UTC
I don't know it is an issue, but it is problem for me. I am using this code (if you need)

    tippy('.tippy-parent', {
        target: '.tippy-child',
        animation: 'shift-away',
        animateFill: false,
        theme: 'google'
    });

    tippy('.tippy', {
        animation: 'shift-away',
        animateFill: false,
        theme: 'google',
    });

And here is .gif for more detail:
https://vgy.me/wFcjKz.gif

**Comment by atomiks** [comment] 2018-12-07 20:34
Browser? Can you make a CodePen please

**Comment by bilalmalkoc** [comment] 2018-12-07 21:06
It not happens in codepen. I don't understans 😞 
https://codepen.io/wpuzman/pen/vvBpoY

**Comment by atomiks** [comment] 2018-12-07 21:08
> If i share my site, can you check it?
Yeah go ahead

Guess it might be some weird CSS causing a problem?

**Comment by bilalmalkoc** [comment] 2018-12-07 21:23
I don't think so. Because i don't use css for this tooltip. You can checek [here](https://wpuzman.com).

**Comment by atomiks** [comment] 2018-12-07 21:31
Link to the page with the tooltips?

**Comment by bilalmalkoc** [comment] 2018-12-07 21:37
No. I am not use linked tooltips in that problem is available.

**Comment by atomiks** [comment] 2018-12-07 21:40
I need to see the page with the problem to help

**Comment by bilalmalkoc** [comment] 2018-12-07 21:42
Shared in this comment already

> I don't think so. Because i don't use css for this tooltip. You can checek [here](https://temabak.com).

**Comment by atomiks** [comment] 2018-12-07 21:43
Ok that link is different now... let me check.

**Comment by atomiks** [comment] 2018-12-07 21:50
Looks like the problem is caused by event delegation (`target`). Not sure why it works on the CodePen and not the site, just yet... 🤔

**Comment by bilalmalkoc** [comment] 2018-12-07 21:54
I must use `target` because of ajax call. Same to here, why it works codepen and not works my site.

**Comment by atomiks** [comment] 2018-12-07 21:58
It looks like you're using `3.1.1`. It appears to be fixed in `3.3.0`, I just pasted the new version in the console and called it with those options. I think it's because `showOnInit` was deferred by 20ms before but now it's not. 🎉

**Closed by atomiks** 2018-12-07 21:58 UTC

**Comment by bilalmalkoc** [comment] 2018-12-07 22:01
Yes it fixed. Hate 3.1.1 😄
